### PR TITLE
Data interface

### PR DESCRIPTION
**Pull request by planck2007**
Created a function get_group_subgroup into hdf5files.py. This function returns the group and subgroup of a given HK parameter

### CODE REVIEW

**Comment by ziotom78** [comment]
Sorry, I am not able to understand why there are so many conflicts in the code; `VALID_GROUPS` and `VALID_SUBGROUPS` have been redefined, but it's not clear which definition should be the one to use. Could you please have a look and fix them?

It would be nice to have some tests for the new function in `stripelline/test`. Have a look at `stripeline/test/test_calibration.py` for an example.

**Comment by planck2007** [comment]
Could you please provide me with more details about this conflicts? I do not understand what the problem is

**Comment by ziotom78** [comment]
> Could you please provide me with more details about this conflicts? I do not understand what the problem is

The current version of the code (commit 29dba93a019e7d80961fc4559acd76ad9cd7f666, Apr 14) has the lines

```python
VALID_GROUPS = ["BIAS", "DAQ"]
VALID_SUBGROUPS = ["POL", "BOARD"]
```

but your patch swaps their value:

```python
VALID_GROUPS = ["BIAS", "DAQ"]
VALID_SUBGROUPS = ["POL", "BOARD"]
```

These conflicts are shown by GitHub if you press the button "Resolve conflicts". I do not understand which values are correct, nor if this change affects some other code. Given that you were the author of the commit on Apr 14, you surely know better than me what's the correct value for these variables. Once you fix the conflict using the button "Resolve conflict", I'll merge this.

**Comment by planck2007** [comment]
Groups and subgroups were swapped following a request of F. Cuttaia (that should have been done here, I know). The point is that the new organization in groups and subgroups reflects the hardware. We have BIAS and DAQ physical boards and for each we can set parameters for polarimeters (POL) or boards (BOARD).

Consider that in your comment you repeated twice the same structure, but I think you meant that in the current version of the code the situation is:

The current version of the code (commit 29dba93, Apr 14) has the lines

VALID_GROUPS = ["POL", "BOARD"]
VALID_SUBGROUPS = ["BIAS", "DAQ"]

**Pull request closed without merging**
